development: &development
  adapter: postgresql
  host: localhost
  database: diner_dev
  encoding: unicode
  
test: &test
  adapter: postgresql
  host: localhost
  database: diner_test
  encoding: unicode